### ISSUE TITLE
Lỗi IPN momo

### ISSUE THREAD

**Issue by bluedrank** [phpviet/laravel-omnipay#1]
The `partnerCode` parameter is required {"exception":"[object] (Omnipay\\Common\\Exception\\InvalidRequestException(code: 0): The `partnerCode` parameter is required at public_html/vendor/phpviet/omnipay-momo/src/Message/AbstractRequest.php:32)
Hiện tại em đang gặp tình huống này nhưng không biết giải quyết thế nào. có ai đã từng gặp có thể hướng dẫn em với ạ. Em đang xử lý tới phần IPN của momo gửi về thì gặp lỗi nói trên, thử debug thì em thấy value của các param bị rỗng trong khi request của momo gửi về thì vẫn đầy đủ, mong các cao nhân chỉ dạy.

**Comment by vuongxuongminh** [comment]
`partnerCode` khi khởi tạo gateway bị thiếu đó bạn, bạn check file `laravel-omnipay.php` trong thư mục config đã điền đầy đủ thông tin cổng chưa?

**Comment by bluedrank** [comment]
> `partnerCode` khi khởi tạo gateway bị thiếu đó bạn, bạn check file `laravel-omnipay.php` trong thư mục config đã điền đầy đủ thông tin cổng chưa?

Dạ đủ hết rồi anh ạ. Em đang bó tay ở phần này, nhưng em đọc tài liệu của MOMO cung cấp thì phần này có vẻ sai Omnipay\MoMo\Message\AllInOne\NotificationRequest tại  method getIncomingParametersBag() thì data của momo gửi sang ko phải json nó là 1 POST và $this->httpRequest->getContent() get ra rỗng nên xuất hiện lỗi đó, em thử thay bằng $this->httpRequest->request->all() thì qua đc chỗ đó nhưng lại sai tại phần chữ ký (2 chữ ký ko khớp) :( anh có cao kiến gì ko ạ?

**Comment by bluedrank** [comment]
> `partnerCode` khi khởi tạo gateway bị thiếu đó bạn, bạn check file `laravel-omnipay.php` trong thư mục config đã điền đầy đủ thông tin cổng chưa?

Dạ đã đủ anh ạ em đã debug trc khi send thì đã thấy đầy đủ các param rồi. nhưng tại phần Omnipay\MoMo\Message\AllInOne\NotificationRequest.php trong method getIncomingParametersBag() biến $json trả về rỗng nên báo lỗi vậy. em có đọc qua document của momo thì tại đây nó sẽ post 1 request kết quả sang bên mình chứ ko phải dạng json. hiện tại em thử thay đổi chỗ đó thành $data = $this->httpRequest->request->all(); thì đã chạy nhưng ko biết có ảnh hưởng tới phần nào khác ko. em chưa đọc được hết suorce và em hơi kém OOP nên đọc thấy mông lung nhiều chỗ quá, anh thử check xem chỗ em fix có đúng ko ạ

**Comment by vuongxuongminh** [comment]
Đã xử lý https://github.com/phpviet/omnipay-momo/commit/1ac1339d15eb5aaecdf5e007790d1c294d053199 bạn chờ ít phút sau đó update composer nhé. Cảm ơn bạn đã báo lỗi.
