### ISSUE TITLE
Problems installing packages into the project

### ISSUE THREAD

**Issue by hoangphidev** [phpviet/laravel-omnipay#14]
I am using laravel 8 and have the problem below when installing package into project. Hope to get help.

![image](https://user-images.githubusercontent.com/32218935/111015970-e2bd4d00-83dd-11eb-99ae-ca5bfd60bbb3.png)

**Comment by hoangphidev** [comment]
My error in terminal:

Using version ^1.1 for phpviet/laravel-omnipay
./composer.json has been updated
Running composer update phpviet/laravel-omnipay
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - php-http/guzzle6-adapter 2.x-dev is an alias of php-http/guzzle6-adapter dev-master and thus requires it to be installed too.
    - phpviet/laravel-omnipay[1.1.0, ..., 1.1.x-dev] require illuminate/support ^5.7 || ^6.0 || ^7.0 -> found illuminate/support[v5.7.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely b
ecause it conflicts with another require.
    - php-http/guzzle6-adapter[dev-master, v1.1.0, ..., v1.1.1, v2.0.0, ..., v2.0.2] require guzzlehttp/guzzle ^6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).
    - omnipay/common v3.0-alpha.1 requires symfony/http-foundation ^2.1|^3 -> found symfony/http-foundation[v2.1.0, ..., 2.8.x-dev, v3.0.0-BETA1, ..., 3.4.x-dev] but the package is fixed to v5.2.4 (lock file version) by a partial up
date and that version does not match. Make sure you list it as an argument for the update command.
    - omnipay/common[v3.0-alpha.2, ..., v3.0.2] require symfony/http-foundation ^2.1|^3|^4 -> found symfony/http-foundation[v2.1.0, ..., 2.8.x-dev, v3.0.0-BETA1, ..., 3.4.x-dev, v4.0.0-BETA1, ..., 4.4.x-dev] but the package is fixed
 to v5.2.4 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - ignited/laravel-omnipay 3.2.0 requires illuminate/support ~5|~6|~7 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with ano
ther require.
    - ignited/laravel-omnipay 3.3.0 requires omnipay/common ~3.0 -> satisfiable by omnipay/common[v3.0-alpha.1, ..., 3.0.x-dev (alias of dev-master)].
    - omnipay/common 3.0.x-dev is an alias of omnipay/common dev-master and thus requires it to be installed too.
    - phpviet/laravel-omnipay 1.1.1 requires ignited/laravel-omnipay ^3.2 -> satisfiable by ignited/laravel-omnipay[3.2.0, 3.3.0].
    - omnipay/common[dev-master, v3.0.3, ..., v3.0.5] require php-http/client-implementation ^1 -> satisfiable by php-http/guzzle6-adapter[dev-master, v1.1.0, v1.1.1, v2.0.0, v2.0.1, v2.0.2, 2.x-dev (alias of dev-master)].
    - Root composer.json requires phpviet/laravel-omnipay ^1.1 -> satisfiable by phpviet/laravel-omnipay[1.1.0, 1.1.1, 1.1.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by vuongxuongminh** [comment]
Duplicate #13
