### ISSUE TITLE
Lỗi The `accessKey` parameter is required

### ISSUE THREAD

**Issue by nguyentrongchinh1997** [phpviet/laravel-omnipay#2]
Mình đã điên đầy thủ thông tin accessKey, secretKey, partnerCode và testMode đang để false. Nhưng khi "kiểm tra thông tin notifyUrl do MoMo gửi sang" thì bị báo lỗi này "The `accessKey` parameter is required". Tài mình đang làm việc trong môi trường test của momo. Mong mọi người giải đáp ạ. Cảm ơn

**Comment by vuongxuongminh** [comment]
Bạn có thể show config của bạn được không? Nhân tiện `testMode` bạn phải set là true khi bạn đang ở môi trường sandbox của MoMo bạn nhé.

**Comment by nguyentrongchinh1997** [comment]
> Bạn có thể show config của bạn được không? Nhân tiện `testMode` bạn phải set là true khi bạn đang ở môi trường sandbox của MoMo bạn nhé.
Em đã để true rồi ạ. Có phải do tk momo của em chưa xác thực những vấn đề liên quan như (cập nhật thông tin nhận tiền, giấy chứng nhận doanh nghiệp) không ạ, Config của em như này ạ:
'MoMoQRCode' => [
            'driver' => 'MoMo_QRCode',
            'options' => [
                'accessKey' => 'E4c........',
                'secretKey' => 'uHL........',
                'partnerCode' => 'MOM.......',
                'testMode' => true,
            ],
        ],

**Comment by vuongxuongminh** [comment]
Xin lỗi vì mình đã không để ý đến notification của issue này, bạn đã giải quyết được chưa? nếu chưa bạn show cụ thể cách bạn sử dụng `purchase` lên đây giúp mình nha.

**Comment by tunghoangbhd** [comment]
Anh làm 1 cái về Napas v3 thì tuyệt vời ^^
