### ISSUE TITLE
Tại sao khi thành toán thành công hoặc thất bại thì param lại được push lên url của mình nhỉ. Làm sao để ẩn được ạ.

### ISSUE THREAD

**Issue by dongphan5295** [phpviet/laravel-omnipay#21]
Tại sao khi thành toán thành công hoặc thất bại thì param nó cứ bị dính lên url mình nhỉ ?  Làm sao để ẩn được ạ.

**Comment by dongphan5295** [comment]
![image](https://user-images.githubusercontent.com/57216944/148368615-f99a166d-a4ef-475f-8d68-ca59cb8f06a6.png)

**Comment by vuongxuongminh** [comment]
các params trên là cần thiết giúp chúng ta có thể định danh được transaction và verify request đến từ MoMo, để ẩn nó đi bạn chỉ việc process order trên sau đó redirect về 1 sucess url (success url do bạn thiết kế).
