### ISSUE TITLE
Nhờ hỗ trợ

### ISSUE THREAD

**Issue by TruongAnTGG** [phpviet/laravel-omnipay#4]
![Screen Shot 2020-06-19 at 11 08 09](https://user-images.githubusercontent.com/45954891/85096009-40d94d00-b21d-11ea-906b-bfa4e05274fc.png)

Mình đã cấu hình đúng như hướng dẫn nhưng vẫn gặp lỗi này, xin hỗ trợ giúp. Xin cảm ơn!

**Comment by vuongxuongminh** [comment]
Bạn copy nội dung file config lên đây mình xem nhé.
