### ISSUE TITLE
Làm thế nào test cho môi trường sanbox với VNPay

### ISSUE THREAD

**Issue by khanhnam99** [phpviet/laravel-omnipay#5]
Làm thế nào test cho môi trường sanbox với VNPay
$gateway = Omnipay::create('VNPay');
        $gateway->initialize([
            'vnp_TmnCode' => '',
            'vnp_HashSecret' => '',
        ]);

        $response = $gateway->purchase([
            'vnp_TxnRef' => time(),
            'vnp_OrderType' => 100000,
            'vnp_OrderInfo' => time(),
            'vnp_IpAddr' => '127.0.0.1',
            'vnp_Amount' => 1000000,
            'vnp_ReturnUrl' => 'https://github.com/phpviet',
        ])->send();

Thấy trong PurchaseRequest có
class PurchaseRequest extends AbstractSignatureRequest{

    protected $productionEndpoint = 'https://pay.vnpay.vn/vpcpay.html';
    protected $testEndpoint = 'http://sandbox.vnpayment.vn/paymentv2/vpcpay.html';

**Comment by vuongxuongminh** [comment]
$gateway = Omnipay::create('VNPay');
$gateway->initialize([
'vnp_TmnCode' => '',
'vnp_HashSecret' => '',
]);

**Comment by khanhnam99** [comment]
thanks
